name: Self-hosted CI example

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: self-hosted
    steps:

      - uses: actions/checkout@v2
      - name: Show directory listing
        shell: bash -l {0}
        run: |
          ls -la
      - name: Cuda compiler version
        run: |
          . /etc/profile.d/cuda.sh
          nvcc --version
      - name: Compile example
        run: |
          . /etc/profile.d/cuda.sh
          nvcc -o hello_houston.exe hello_houston.cu
      - name: Run example
        run: |
          ./hello_houston.exe
