job build:
  image:
    "ubuntu:18.04"
  variables:
    PYTHON_VERSION: "3.7"
  script:
    - apt-get update && apt-get install -y wget git build-essential
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no --set auto_update_conda False
    # Useful for debugging any issues with conda
    - conda info -a
    # Install python env
    - conda create --name ci_for_science python=${PYTHON_VERSION}
    - source activate ci_for_science

    # Install your conda dependencies
    - conda install numpy cython

    # Clone the repo and run the test
    - cd $HOME && git clone --branch master --single-branch https://github.com/NLeSC/ci_for_science.git
    - cd ci_for_science && pip install -e .[test]
